name: CI workflow
on: [push]
permissions:
  id-token: write
  contents: read
jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node.js 
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci 
      - name: Print node node-version
        run: node --version
      - name: Run tests
        run: npm test
      - name: AWS credentials configuration
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::047719635525:role/GitHubActions-ECR-Push-Role
          aws-region: ap-south-1
      - name: verify aws
        run: aws sts get-caller-identity
      - name: Docker build
        run: docker build -t node-app .
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Tag the image
        run: docker tag node-app 047719635525.dkr.ecr.ap-south-1.amazonaws.com/node-app:${{ github.sha }}
        

